#!/bin/sh

#connect Vbuddy to WSL
~/Documents/iac/lab0-devtools/tools/attach_usb.sh

# cleanup
rm -rf obj_dir
rm -f top.vcd

# run Verilator to translate Verilog into C++, including C++ test bench
verilator -Wall --cc --trace top.sv counter.sv bin2bcd.sv --exe top_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# run executable simulation file
obj_dir/Vtop

#config vbuddy.cfg
ls /dev/ttyU* > vbuddy.cfg